services:
  postgres-parquet-extensions:
    image: postgres-parquet-extensions
    shm_size: 256m
    restart: unless-stopped
    container_name: 'postgres-parquet-extensions'
    build:
      context: .
      dockerfile: Dockerfile
    command: postgres -c 'max_connections=200' -c 'client_connection_check_interval=60000'
    environment:
        POSTGRES_DB: 'blockscout'
        POSTGRES_USER: 'blockscout'
        POSTGRES_PASSWORD: '12345'
    ports:
      - target: 5432
        published: 7432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./parquet_files:/home/blockscout/parquet_files
volumes:
  pgdata:
